### ISSUE TITLE
Env vars for services

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#429]
Environment variable support for individual services will be provided in the form:
```
#service.yml

environment:
  development:
    public:
      ENV1: some value
      ENV2: some value
    secret:
      - ENV3
  production:
    public:
      ENV1: some value
      ENV2: some value
    secret:
      - ENV3
```

The secret keys can be set in development via https://github.com/joho/godotenv. The user will define a `.env` file containing the values of the secret env vars. Both `public` and `secret` env vars and values will be rendered into `tmp/docker-compose.yml` which is not checked in with the app. 

As for production, the `public` env vars and values will be rendered into the terraform directly, whereas the `secret` env vars will be represented as variables in the terraform, the values of which should be managed via `exo configure`. During `exo deploy` these secrets will be read from the remote store that `exo configure` manages.

**Comment by hugoesthere** [comment]
@kevgo @charlierudolph thoughts?

**Comment by kevgo** [comment]
What is the use case for this?

**Comment by hugoesthere** [comment]
The use case is for any service that would ever need to set an environment variable. Right now exosphere provides no way of doing this. For the `secret` env vars, there could be a need for things like API keys, db credentials, etc. 

 This issue was ported over from: https://github.com/Originate/exosphere-sdk/issues/301.

**Comment by hugoesthere** [comment]
@kevgo where do we land on this? This is needed for `exo-deploy`.

It would probably be a better idea for the production field of `service.yml` to look like this:
```
  production:
    public:
      ENV1: some value
      ENV2: some other value
    secret:
      ENV3: secret_key
```

Eventually we need some way to render an env var block in Terraform that looks like this:
```
environment_variables = {
  ENV1 = "some value"
  ENV2 = "some other value"
  ENV3 = "${var.secret_key}"
}
```

The value of `secret_key` is stored in the `secrets.tfvars` file we're managing for the user. That file is pulled down during `terrafrom plan/apply` and pointed to via `-var-file=secrets.tf`. This means the `secret_key` would have to be unique across services.

**Comment by hugoesthere** [comment]
@alexdavid

**Comment by charlierudolph** [comment]
hmm. @hugobho can we keep the structure the same between dev and production? Maybe for dev we can use 

```
public:
  ENV1: some value
  ENV2: some value
secret:
  ENV3: ENV_VARIABLE_NAME
```

**Comment by hugoesthere** [comment]
Then the user would refer to that secret variable as `ENV3` in their source code but `ENV_VARIABLE_NAME` when running `exo-run` right? Maybe we could revert to our initial idea
```
public:
      ENV1: some value
      ENV2: some value
secret:
      - ENV3
```
And just enforce that secret variables have to use that variable name everywhere. In the source code as `process.env.ENV3` and during execution as `env ENV3=some_value exo run`. The `secrets.tf` file would look like `ENV3="some_value:` and the Terraform `ENV3 = "${var.ENV3}"`

**Comment by alexdavid** [comment]
I think we wanted to start using [vault](https://www.vaultproject.io/) for project specific secrets. Maybe exosphere should integrate with that.

@chrizkim

**Comment by hugoesthere** [comment]
This is one of the last things we have to do to get a functioning `exo deploy`

**Comment by chrizkim** [comment]
+1 for using Vault for secrets

**Comment by hugoesthere** [comment]
Should we write a wrapper around vault or use it directly?

**Comment by chrizkim** [comment]
@hugobho I think we'll want to wrap, similar to how `exo deploy` wraps `terraform ...` commands

**Comment by hugoesthere** [comment]
@alexdavid and I discussed this and we're going to go with the following implementation:
```
environment:
  default:
    env1: value1
    env2: value2
  development:
    env1: dev_value1
  production:
    env1: prod_value1
  secrets:
    - env3
    - env4
```

Then env vars set in default will be used in all environments, and those specified lower down will overwrite the env vars with the same key above them. In development, all env vars are passed into the Docker container during run-time, with secret values being set by a user locally. In deployment, all env vars are passed in as command line arguments to the Terraform commands, with the secret values being pulled down from a remote S3 bucket. @alexdavid does this sound like what we discussed?

**Comment by charlierudolph** [comment]
Done for production, still todo for dev

**Comment by hugoesthere** [comment]
Seems like we have duplicate fields for service env vars now:
```
docker:
  ports:
    - 3000:3000
  environment:
    - env1: dev_value

environment:
  default:
  development:
    env1: dev_value
```

@charlierudolph @alexdavid @kevgo what are you guys' thoughts on consolidating them? And maybe moving that port mapping field elsewhere so we can get rid of the `docker` field completely? I think it makes more sense to keep things under `development/production` than in `docker/terraform` or something like that.

**Comment by alexdavid** [comment]
So thinking further on this, since sometimes development and production may differ we should specify port and environment in both under keys `development` and `production`. However, we can use yaml's built-in extend to handle defaulting for the user:

```yaml
defaults: &defaults
  ports: [8080]
  environment:
    env1: dev_value

development:
  <<: *defaults

production:
  <<: *defaults
  ports: [80]
```

I just verified and this works out of the box with go's yaml parser.

Also I think environment should be an object not an array
