### ISSUE TITLE
exo deploy: ability to deploy to multiple environments

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#498]
I want to be able to use exo-deploy to deploy multiple environments such as dev / qa / staging / production. We already have the idea of a `dev` section which may need to be renamed to `local`.

@hugobho update this issue as we discover more about the requirements / how we would do this

**Comment by charlierudolph** [comment]
@alexdavid @hugobho checking in on this.

Is our solution here that you deploy to a different region / with a different AWS account?

**Comment by hugoesthere** [comment]
We haven't decided yet. I believe that @alexdavid and @chrizkim are going to discuss this soon.

**Comment by charlierudolph** [comment]
For supporting multiple environments what do you guys think of the following. The user can use yml built ins for dealing with the remote defaults. This also allows them to deploy to different aws accounts and regions if they want but they can also use the same account and different regions if they choose. The following assumes #837 is done. `exo deploy` would have a new required parameter of what remote is being deployed.

application.yml
```yml
# current
remote:
  dependencies:
  url:
  region:
  account-id:
  ssl-certificate-arn:

# new
remote:
  qa:
    dependencies:
    url:
    region:
    account-id:
    ssl-certificate-arn:
  production:
    dependencies:
    url:
    region:
    account-id:
    ssl-certificate-arn:
```
service.yml
```yml
# current
remote:
  dependencies:
  url:
  cpu:
  memory:
  environment:

# new
remote:
  qa:
    dependencies:
    url:
    cpu:
    memory:
    environment:
  production:
    dependencies:
    url:
    cpu:
    memory:
    environment:
```

@alexdavid @hugobho

**Comment by hugoesthere** [comment]
Did we decide how we were deploying to multiple envs on the AWS side of things? Are we deploying to different regions or something? I don't remember coming to a conclusion on that

**Comment by charlierudolph** [comment]
I don't think that matters for this as it is flexible enough to support either solution of different regions versus different AWS accounts

**Comment by charlierudolph** [comment]
For now working off

application.yml
```yml
# current
remote:
  dependencies:
  url:
  region:
  account-id:
  ssl-certificate-arn:

# new
remote:
  dependencies:
  environments:
    qa:
      url:
      region:
      account-id:
      ssl-certificate-arn:
    production:
      url:
      region:
      account-id:
      ssl-certificate-arn:
```
service.yml
```yml
# current
remote:
  dependencies:
  url:
  cpu:
  memory:
  environment:

# new
remote:
  dependencies:
  cpu:
  memory:
  environments:
    qa:
      url:
      environment:
    production:
      url:
      environment:
```
