### ISSUE TITLE
short term solution for databases

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#508]
On `space-tweet`, in order to deploy the mongo dependency had to be commented out as that had been setup manually. I'd suggest we update `exo deploy` to filter out dependencies named mongo / postgres (for EDX) for the short term so we can set them up manually and use exo deploy while db support is added.

@hugobho @mcharawi @kevgo thoughts?

**Comment by hugoesthere** [comment]
We could also define a field in `config` that says `ignoreInProduction` or something like that

**Comment by charlierudolph** [comment]
I like the idea of the flag as it gives an indication that it was manually setup.

**Comment by kevgo** [comment]
Ideally, we have drivers for app dependencies that know what to do with it:
- whether to boot up a Docker image or not
- how to boot up the Docker image (Exocom is only a single instance)
- how to provide info about the dependency to services

Then the postgres driver knows to spin up an RDS instance, while the Mongo driver knows to read the config data about the mongolab account from the config file and provides that to the services that use Mongo.

**Comment by hugoesthere** [comment]
Even for a specific driver, we might still want to have some option that says "spin up RDS instance", or "create 3rd party db", otherwise we pigeonhole the user into a single way of using a particular db in production right?

I'd also imagine that these dbs need their own configuration, in which case the `config` field of a dependency needs to grow. Maybe even split into a `dev-config` and `prod-config`

**Comment by hugoesthere** [comment]
As for a short term solution, @charlierudolph by flag do you mean defining a field in `config`?

**Comment by charlierudolph** [comment]
yes

**Comment by kevgo** [comment]
I think in the medium-term we have to provide the ability to configure dependencies like databases specific for each environment anyways. For example,  when my app uses Postgres, I want to have these options:

- in dev mode: (a) use a locally installed version, or (b) spin one up in Docker
- in prod mode: (a) use a third-party account, or (b) create and use an RDS instance
- in QA mode: (a) use a different third-party account, or (b) spin up a different RDS instance

Could we use this approach to solve our short-term issues as well? We don't have to support all options right from the start, if the only option in production is "third-party account", that's fine for now.

The way this could be implemented is that we keep the current `dependencies` block in `application.yml`, and add a `dependencies` block to the `environments/development` and `environments/production` sections, where configuration settings can be overridden for those environments.

**Comment by hugoesthere** [comment]
Yes, I suppose the single flag to "ignore a dependency" could instead be "third-party account". 

This is closer to what the environments block looks like: https://github.com/Originate/space-tweet/blob/e03ff2366720d6e0349a5d51db0c835267c98872/application.yml#L21 So app.yml would look more like this:
```
production:
  url: originate.com
  dependency-config: 
    mongo: third-party
    post-gres: RDS

development:
  dependency-config:
    mongo: local
    post-gres: docker
```

Perhaps then this dependency `config` block should be moved into these new blocks? (https://github.com/Originate/space-tweet/blob/e03ff2366720d6e0349a5d51db0c835267c98872/application.yml#L10) So then it looks closer to:
```
development:
  dependency-config:
    mongo: 
      type: local
      config:
        endpoint: mongo://...
    post-gres
      type: docker
      config:
        ports: 3000:3000
        online-text: 'i am online'
```
