### ISSUE TITLE
Long term solution for dbs and third party dependencies

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#559]
Per our discussion here: https://github.com/Originate/exosphere/issues/508, we are going with a more permanent solution to third party dependencies in production. What do we think about this proposed format in `application.yml` taken from the discussion in #508:
```
development:
  dependencies:
    - name: exocom
      version: 0.24.0
    - name: mongo
      version: 3.4.0
       silent: true
       config:
          ...

production:
  dependencies
    - name: exocom
      version: 0.24.0
    - name: mongo
      version: 3.4.0
      config:
         ...
```
