### ISSUE TITLE
exo-test: erroring on EDX

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#582]
https://circleci.com/gh/Originate/EDX/49

Was working for 0.23.0.alpha.4 and started failing when upgraded to 0.23.0.alpha.5.

![screen shot 2017-09-19 at 6 38 02 pm](https://user-images.githubusercontent.com/1676758/30622966-b66312ca-9d69-11e7-8944-8fc1685d5541.png)

@hugobho @alexdavid you ever seen anything like this or have any idea what could be going wrong

**Comment by charlierudolph** [comment]
This works locally but not on CI.
The docker compose file on CI is:
```
version: "3"
services:
  bank-service:
    build:
      context: /home/circleci/EDX/bank-service
      dockerfile: Dockerfile.dev
    command: bin/test
    container_name: bank-service
    volumes:
    - /home/circleci/EDX/bank-service:/mnt
    links:
    - postgres9.6.4:postgres
    environment:
      DATABASE_NAME: edx
      DATABASE_PASSWORD: mypassword
      DATABASE_USERNAME: myuser
      EXOCOM_HOST: exocom0.26.1
      POSTGRES: postgres
      ROLE: bank-service
    depends_on:
    - postgres9.6.4
  postgres9.6.4:
    image: postgres:9.6.4
    container_name: postgres9.6.4
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: edx
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
```
