### ISSUE TITLE
rds app dependency: auto inject variables

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#617]
database name, username, password to service

Should not need to be defined in all services. For config may need to determine what those vars get injected as

**Comment by hugoesthere** [comment]
The new format as we discussed:
```
name: postgres
version: 9.6.4
config:
  rds:
    allocated-storage: 10
    db-name: edx
    username: edxdevuser
    password-secret-name: RDS_MASTER_PASSWORD
    instance-class: db.t2.micro
    service-env-var-names:
      db-name: DATABASE_NAME
      username: DATABASE_USERNAME
      password: DATABASE_PASSWORD
    storage-type: gp2
```
