### ISSUE TITLE
committing docker-compose files

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#746]
I don't think we can encourage this yet as we are currently using absolute paths in them which would change between developer machines. Should we switch back to relative paths or do we have other options?

Example service in docker-compose file
```yml
services:
  bank-customer-service:
    build:
      context: /Users/charlesrudolph/projects/EDX/bank-customer-service
      dockerfile: Dockerfile.dev
    command: yarn start
    container_name: bank-customer-service
    volumes:
    - /Users/charlesrudolph/projects/EDX/bank-customer-service:/mnt
    links:
    - postgres9.6.4:postgres
    environment:
      DATABASE_NAME: edx
      DATABASE_PASSWORD: mypassword
      DATABASE_USERNAME: myuser
      EXOCOM_HOST: exocom0.26.4
      LOGGLY_API_KEY: ""
      LOGGLY_SUBDOMAIN: ""
      POSTGRES: postgres
      ROLE: bank-customer-service
    depends_on:
    - exocom0.26.4
    - postgres9.6.4
    restart: on-failure
```
@alexdavid @hugobho

**Comment by alexdavid** [comment]
I think we would need to do something like

```yaml
context: "${APP_PATH}/bank-customer-service"

# ...

volumes:
  - "${APP_PATH}/bank-customer-service:/mnt"
```

And inject the `APP_PATH` env variable when running `docker-compose`
