### ISSUE TITLE
extract production dependencies

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#751]
In order to make these more pluggable:
* remove the go code associated with exocom/nats/rds production dependencies
~* `DEPENDENCY_<name>_HOST` should be injected into services automatically~
* A production dependency template should be a terraform template and readme with a suggestion of what docker image to use in development and what should be specified in the config
  * could possibly include a yml file listing the keys it expects to be present in the config that exosphere could validate.
  * the template will be passed a config object (from app/service.yml)
  * for now can live in new `production-dependency-templates` folder in this repo (can extract to own repo later / add in ability to load other templates)
* the dependency will have the following structure when used in app/service.yml
    ```yml
    template: <name>
    template-config:  
       engine: postgres
       password_secret_name: some_key
       ...
    ``` 
   ~the merged config key/values will also be passed as service env vars as `DEPENDENCY_<NAME>_CONFIG_<KEY>`~

@hugobho @alexdavid please review
