### ISSUE TITLE
development generic dependencies

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#755]
update so the user specifies an image (allowing for using name-spaced images) and a name.

```yml
# current 
dependencies: 
  # (mongo3.0.4 becomes the service name) 
  - name: mongo
    version: 3.0.4

# new
dependencies: 
  # (my-custom will be the service name)
  my-custom:
    image: 'mongo:0.26.4'
```

Also note that switching to using an object means we will need to sort by the dependency name in order to ensure out docker-compose file stays consistent.

@alexdavid please review to see if this captures the issue you ran into yesterday

**Comment by alexdavid** [comment]
👍 I also like that we join the imagename/version like the docker convention.

What are your thoughts on not making this an array and instead making the dependencies a map from name -> configuration
```yaml
my-custom:
  image: 'mongo:0.26.4'
  config: {}
```

Wouldn't this make it easier to merge the service and application dependencies?

**Comment by charlierudolph** [comment]
I'm fine with that I don't think there is a reason for deps being an array.

**Comment by hugoesthere** [comment]
Should we also get rid of referring to a dependency as `#{dependency_name}#{version}`? We use this in several places such as for docker-compose.yml keys and container names. We had this initially to support the same dependency of different versions.

**Comment by charlierudolph** [comment]
I believe we can get rid of referring to it by `#{dependency_name}#{version}` since we will now use the custom name. With this new version they can still use the same dependency with different versions of even now multiple copies of the same dependency.

**Comment by charlierudolph** [comment]
Tied to this I think we can do the following
```yml
local:
  - name:
    version:
    config:

remote:
  - name:
    version:
    config:

# becomes

local:
  <id>:
     type: (exocom|nats|generic) # generic by default, field goes away once everything is generic
     image: # always required
     config: 

remote:
  <id>:
     type: (exocom|rds|generic) # for rds name & version for rds moves into config as engine & engineVersion, for exocom version moves into config
     config:
```

Would be done in two parts. Local first and then remote second. 
@hugobho @alexdavid thoughts
