### ISSUE TITLE
generalize service data env var for dependencies 

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#756]
Want to do this in order to remove exocom's code for loading the service routes. Maybe something like:

```yml
# service1/service.yml
dependency-data:
  exocom:
    a: b

# service2/service.yml
dependency-data:
  exocom:
    c: d

# application.yml
services:
  serviceA:
    location: './service1'
    dependeny-data:
      exocom:
        e: f
  serviceB:
    location: './service2'
```
Then exocom would receive the env var `SERVICE_DATA` with the content
```json
{
  "serviceA": {
    "a": "b",
    "e": "f"
  },
  "serviceB": {
    "c": "d"
  }
}
```
This should allow us to delete `compileServiceRoutes` from `config.exocomDevelopmentDependency`

The following should also be removed since they are exocom specific:
* `MessageTranslations` from `types.ServiceData` 
* `ServiceMessages` from `types.ServiceConfig`

Exocom will need to be updated to support this new version of env variables

@alexdavid @hugobho thoughts?
