### ISSUE TITLE
service env vars: local/remote

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#801]
In service.yml environment we currently have the block
```yml
environment:
  default:
  development:
  production:
  secrets:
```
* Update `development` / `production` to `local` / `remote`.
* `local` will apply for any use of `exo run`
* `remote` will apply for deployments

@alexdavid @hugobho please review
