### ISSUE TITLE
service dependencies: local/remote

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#802]
Currently `service.yml` has
```yml
development:
  dependencies:
  scripts:
  port:

production:
  dependencies:
  url:
  cpu:
  memory:
  port:
  health-check:
```

Update this to
```yml
development:
  scripts:
  port:

production:
  port:

local:
  dependencies:

remote:
  dependencies:
  url:
  cpu:
  memory:
  health-check:
```

@alexdavid @hugobho please review
