### ISSUE TITLE
application dependencies: local/remote

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#803]
Currently `application.yml` has
```yml
development:
  dependencies:

production:
  dependencies:
  url: 
  region: 
  account-id: 
  ssl-certificate-arn: 
```
Update this to
```yml
local:
  dependencies:

remote:
  dependencies:
  url: 
  region: 
  account-id: 
  ssl-certificate-arn: 
```
@alexdavid @hugobho please review
