### ISSUE TITLE
rename environment to environment-variables

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#926]
```yml
# Before
local:
  environment:

remote:
  environment:

# After
local:
  environment-variables:

remote:
  environment-variables:
```
