### ISSUE TITLE
configuration for host port assignment

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#959]
Ability to specify what port to start counting from, and ability to specify a host port for a given service. I think the service override should be in the `application.yml` in order to support reusable services.

```yml
services:
  service1:
    location:
    host_port: # specify dedicated host port for this service

initial_host_port: # specify what port to start counting from
```

@hugobho @alexdavid @Bowbaq @dminnear @bishtawi @allensallinger thoughts?
